/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_ccdongyu_jni_JNITest */

#ifndef _Included_pers_ccdongyu_jni_JNITest
#define _Included_pers_ccdongyu_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_ccdongyu_jni_JNITest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pers_ccdongyu_jni_JNITest_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
